// <auto-generated />
using CustomerTracking.Infrastructure.Persistense;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerTracking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927043820_initial_Migration")]
    partial class initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerTracking.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId", "Name")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernorateId = 1,
                            Name = "Nasr City"
                        },
                        new
                        {
                            Id = 2,
                            GovernorateId = 1,
                            Name = "Maadi"
                        },
                        new
                        {
                            Id = 3,
                            GovernorateId = 1,
                            Name = "Heliopolis"
                        },
                        new
                        {
                            Id = 4,
                            GovernorateId = 1,
                            Name = "Downtown Cairo"
                        },
                        new
                        {
                            Id = 5,
                            GovernorateId = 1,
                            Name = "New Cairo"
                        },
                        new
                        {
                            Id = 6,
                            GovernorateId = 2,
                            Name = "Sidi Gaber"
                        },
                        new
                        {
                            Id = 7,
                            GovernorateId = 2,
                            Name = "Miami"
                        },
                        new
                        {
                            Id = 8,
                            GovernorateId = 2,
                            Name = "Smouha"
                        },
                        new
                        {
                            Id = 9,
                            GovernorateId = 2,
                            Name = "Montaza"
                        },
                        new
                        {
                            Id = 10,
                            GovernorateId = 2,
                            Name = "Al Agamy"
                        },
                        new
                        {
                            Id = 11,
                            GovernorateId = 3,
                            Name = "Dokki"
                        },
                        new
                        {
                            Id = 12,
                            GovernorateId = 3,
                            Name = "Mohandessin"
                        },
                        new
                        {
                            Id = 13,
                            GovernorateId = 3,
                            Name = "6th of October"
                        },
                        new
                        {
                            Id = 14,
                            GovernorateId = 3,
                            Name = "Haram"
                        },
                        new
                        {
                            Id = 15,
                            GovernorateId = 3,
                            Name = "Sheikh Zayed"
                        },
                        new
                        {
                            Id = 16,
                            GovernorateId = 4,
                            Name = "Banha"
                        },
                        new
                        {
                            Id = 17,
                            GovernorateId = 4,
                            Name = "Shubra El Kheima"
                        },
                        new
                        {
                            Id = 18,
                            GovernorateId = 4,
                            Name = "Qalyub"
                        },
                        new
                        {
                            Id = 19,
                            GovernorateId = 5,
                            Name = "Mansoura"
                        },
                        new
                        {
                            Id = 20,
                            GovernorateId = 5,
                            Name = "Talkha"
                        },
                        new
                        {
                            Id = 21,
                            GovernorateId = 5,
                            Name = "Mit Ghamr"
                        },
                        new
                        {
                            Id = 22,
                            GovernorateId = 6,
                            Name = "Zagazig"
                        },
                        new
                        {
                            Id = 23,
                            GovernorateId = 6,
                            Name = "10th of Ramadan"
                        },
                        new
                        {
                            Id = 24,
                            GovernorateId = 6,
                            Name = "Belbeis"
                        },
                        new
                        {
                            Id = 25,
                            GovernorateId = 7,
                            Name = "Tanta"
                        },
                        new
                        {
                            Id = 26,
                            GovernorateId = 7,
                            Name = "Al Mahalla Al Kubra"
                        },
                        new
                        {
                            Id = 27,
                            GovernorateId = 7,
                            Name = "Kafr El Zayat"
                        },
                        new
                        {
                            Id = 28,
                            GovernorateId = 8,
                            Name = "Shibin El Kom"
                        },
                        new
                        {
                            Id = 29,
                            GovernorateId = 8,
                            Name = "Menouf"
                        },
                        new
                        {
                            Id = 30,
                            GovernorateId = 8,
                            Name = "Sadat City"
                        },
                        new
                        {
                            Id = 31,
                            GovernorateId = 9,
                            Name = "Damanhur"
                        },
                        new
                        {
                            Id = 32,
                            GovernorateId = 9,
                            Name = "Kafr El Dawwar"
                        },
                        new
                        {
                            Id = 33,
                            GovernorateId = 9,
                            Name = "Rashid"
                        },
                        new
                        {
                            Id = 34,
                            GovernorateId = 10,
                            Name = "Kafr El Sheikh City"
                        },
                        new
                        {
                            Id = 35,
                            GovernorateId = 10,
                            Name = "Desouk"
                        },
                        new
                        {
                            Id = 36,
                            GovernorateId = 10,
                            Name = "Baltim"
                        },
                        new
                        {
                            Id = 37,
                            GovernorateId = 11,
                            Name = "Damietta City"
                        },
                        new
                        {
                            Id = 38,
                            GovernorateId = 11,
                            Name = "Ras El Bar"
                        },
                        new
                        {
                            Id = 39,
                            GovernorateId = 11,
                            Name = "Faraskur"
                        },
                        new
                        {
                            Id = 40,
                            GovernorateId = 12,
                            Name = "Port Fouad"
                        },
                        new
                        {
                            Id = 41,
                            GovernorateId = 12,
                            Name = "Al Manakh"
                        },
                        new
                        {
                            Id = 42,
                            GovernorateId = 12,
                            Name = "Al Zohour"
                        },
                        new
                        {
                            Id = 43,
                            GovernorateId = 13,
                            Name = "Ismailia City"
                        },
                        new
                        {
                            Id = 44,
                            GovernorateId = 13,
                            Name = "Fayed"
                        },
                        new
                        {
                            Id = 45,
                            GovernorateId = 13,
                            Name = "Qantara"
                        },
                        new
                        {
                            Id = 46,
                            GovernorateId = 14,
                            Name = "Suez City"
                        },
                        new
                        {
                            Id = 47,
                            GovernorateId = 14,
                            Name = "Ain Sokhna"
                        },
                        new
                        {
                            Id = 48,
                            GovernorateId = 14,
                            Name = "Arbaeen"
                        },
                        new
                        {
                            Id = 49,
                            GovernorateId = 15,
                            Name = "Arish"
                        },
                        new
                        {
                            Id = 50,
                            GovernorateId = 15,
                            Name = "Sheikh Zuweid"
                        },
                        new
                        {
                            Id = 51,
                            GovernorateId = 15,
                            Name = "Rafah"
                        },
                        new
                        {
                            Id = 52,
                            GovernorateId = 16,
                            Name = "Sharm El Sheikh"
                        },
                        new
                        {
                            Id = 53,
                            GovernorateId = 16,
                            Name = "Dahab"
                        },
                        new
                        {
                            Id = 54,
                            GovernorateId = 16,
                            Name = "Saint Catherine"
                        },
                        new
                        {
                            Id = 55,
                            GovernorateId = 17,
                            Name = "Beni Suef City"
                        },
                        new
                        {
                            Id = 56,
                            GovernorateId = 17,
                            Name = "Nasser"
                        },
                        new
                        {
                            Id = 57,
                            GovernorateId = 17,
                            Name = "Al Fashn"
                        },
                        new
                        {
                            Id = 58,
                            GovernorateId = 18,
                            Name = "Faiyum City"
                        },
                        new
                        {
                            Id = 59,
                            GovernorateId = 18,
                            Name = "Sinnuris"
                        },
                        new
                        {
                            Id = 60,
                            GovernorateId = 18,
                            Name = "Tamiya"
                        },
                        new
                        {
                            Id = 61,
                            GovernorateId = 19,
                            Name = "Minya City"
                        },
                        new
                        {
                            Id = 62,
                            GovernorateId = 19,
                            Name = "Mallawi"
                        },
                        new
                        {
                            Id = 63,
                            GovernorateId = 19,
                            Name = "Beni Mazar"
                        },
                        new
                        {
                            Id = 64,
                            GovernorateId = 20,
                            Name = "Assiut City"
                        },
                        new
                        {
                            Id = 65,
                            GovernorateId = 20,
                            Name = "Dairut"
                        },
                        new
                        {
                            Id = 66,
                            GovernorateId = 20,
                            Name = "Abnub"
                        },
                        new
                        {
                            Id = 67,
                            GovernorateId = 21,
                            Name = "Sohag City"
                        },
                        new
                        {
                            Id = 68,
                            GovernorateId = 21,
                            Name = "Akhmim"
                        },
                        new
                        {
                            Id = 69,
                            GovernorateId = 21,
                            Name = "Girga"
                        },
                        new
                        {
                            Id = 70,
                            GovernorateId = 22,
                            Name = "Qena City"
                        },
                        new
                        {
                            Id = 71,
                            GovernorateId = 22,
                            Name = "Nag Hammadi"
                        },
                        new
                        {
                            Id = 72,
                            GovernorateId = 22,
                            Name = "Qus"
                        },
                        new
                        {
                            Id = 73,
                            GovernorateId = 23,
                            Name = "Luxor City"
                        },
                        new
                        {
                            Id = 74,
                            GovernorateId = 23,
                            Name = "Esna"
                        },
                        new
                        {
                            Id = 75,
                            GovernorateId = 23,
                            Name = "Armant"
                        },
                        new
                        {
                            Id = 76,
                            GovernorateId = 24,
                            Name = "Aswan City"
                        },
                        new
                        {
                            Id = 77,
                            GovernorateId = 24,
                            Name = "Kom Ombo"
                        },
                        new
                        {
                            Id = 78,
                            GovernorateId = 24,
                            Name = "Edfu"
                        },
                        new
                        {
                            Id = 79,
                            GovernorateId = 25,
                            Name = "Hurghada"
                        },
                        new
                        {
                            Id = 80,
                            GovernorateId = 25,
                            Name = "Marsa Alam"
                        },
                        new
                        {
                            Id = 81,
                            GovernorateId = 25,
                            Name = "Safaga"
                        },
                        new
                        {
                            Id = 82,
                            GovernorateId = 26,
                            Name = "Kharga"
                        },
                        new
                        {
                            Id = 83,
                            GovernorateId = 26,
                            Name = "Dakhla"
                        },
                        new
                        {
                            Id = 84,
                            GovernorateId = 26,
                            Name = "Farafra"
                        },
                        new
                        {
                            Id = 85,
                            GovernorateId = 27,
                            Name = "Marsa Matrouh"
                        },
                        new
                        {
                            Id = 86,
                            GovernorateId = 27,
                            Name = "Sallum"
                        },
                        new
                        {
                            Id = 87,
                            GovernorateId = 27,
                            Name = "Sidi Barrani"
                        });
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.CustomerImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerImages", (string)null);
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Governorates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Giza"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Qalyubia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dakahlia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sharqia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gharbia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Monufia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Beheira"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kafr El Sheikh"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Damietta"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Port Said"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ismailia"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Suez"
                        },
                        new
                        {
                            Id = 15,
                            Name = "North Sinai"
                        },
                        new
                        {
                            Id = 16,
                            Name = "South Sinai"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Beni Suef"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Faiyum"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Minya"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Assiut"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sohag"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Qena"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Luxor"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Aswan"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Red Sea"
                        },
                        new
                        {
                            Id = 26,
                            Name = "New Valley"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Matrouh"
                        });
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.City", b =>
                {
                    b.HasOne("CustomerTracking.Domain.Models.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.Customer", b =>
                {
                    b.HasOne("CustomerTracking.Domain.Models.City", "City")
                        .WithMany("Customers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerTracking.Domain.Models.Governorate", "Governorate")
                        .WithMany("Customers")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.CustomerImage", b =>
                {
                    b.HasOne("CustomerTracking.Domain.Models.Customer", "Customer")
                        .WithMany("Images")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.City", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.Customer", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("CustomerTracking.Domain.Models.Governorate", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
